print("Ingrese los datos solicitados")
lastName = input("Ingrese los apellidos")
initialsName = input("Ingrese iniciales del nombre seguido de punto")
year = input("Ingrese año")
title = input("Ingrese título")
city = input("Ingrese ciudad")
publisher = input("Ingrese editorial")
link = input("Ingrese enlace")
print(LastName + ", " + initialsName +" (" + year + "). " + title +  ". " + city + ". " + publisher + ". " + "Recuperado de: " + link)


print("Ingrese los datos solicitados")
corporativeName = input("Ingrese Instituciòn")
year = input("Ingrese año")
title = input("Ingrese título")
city = input("Ingrese ciudad")
publisher = input("Ingrese editorial")
link = input("Ingrese enlace")
print(corporativeName +" (" + year + "). " + title +  ". " + city + ". " + publisher + ". " + "Recuperado de: " + link)

